; -*- lexical-binding: t -*-

(package "space-tree"
         "0.1.0"
         "Tree-based workspace management")

(website-url "https://github.com/chiply/space-tree")
(keywords "convenience" "frames")

(package-file "space-tree.el")
(files "*.el")

(script "test" "eask test ert test/space-tree-test.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "ht" "2.3")
(depends-on "dash" "2.19")

(development
 (depends-on "package-lint"))
